services:
  - name: django-chatbot-app
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_django.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: 'django-insecure-7*9qu)1j=ihwh9q9x0s79g*f7ztf-8w+nb)@m#e_ywg+22z7f6' # Your secret key
      - key: DEBUG
        value: 'false'
      - key: ALLOWED_HOSTS
        value: django-chatbot-app.onrender.com
      - key: DATABASE_URL
        value: sqlite://///Users/mac/Documents/chatbot_django/chatbot_django/db.sqlite3 # Or point to a production DB if available
      - key: TIME_ZONE
        value: UTC

  - name: chatbot
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run chatbot.py
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_ENV
        value: production

  - name: practice
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run practice.py
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8502
      - key: STREAMLIT_ENV
        value: production
